version: '3'

services:
    database:
        image: postgres:11-alpine
        volumes:
            - guestbook-db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports: [5432]

volumes: 
    guestbook-db:
